.Dd July 17, 2023
.Dt BACKUPFS 1
.Sh NAME
.Nm backupfs
.Nd mount & unmount the backup partition
.Sh SYNOPSIS
.Nm
.Op Fl hmu
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl m
mount the backup partition
.It Fl u
unmount the backup partition
.El
.Sh ENVIRONMENT
Make sure to set BACKUPFS_BACKUP_PARTITION_UUID before running
.Nm .
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
