.Dd September 3, 2022
.Dt BOOKOPEN 1
.Sh NAME
.Nm bookopen
.Nd select a book from the library to open with zathura
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Ar dir
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
