.Dd January 13, 2023
.Dt BOOKMARKSU 1
.Sh NAME
.Nm bookmarksu
.Nd chrome bookmarks parser
.Sh SYNOPSIS
.Nm
.Op Fl eht
.Sh OPTIONS
.Bl -tag -width indent
.It Fl e
extracts all links from bookmarks file
.It Fl h
show usage
.It Fl t
resolve website title using wget
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
