.Dd September 3, 2022
.Dt MKSH 1
.Sh NAME
.Nm mksh
.Nd create the skeleton of a script
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Ar script_name
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
