.Dd September 3, 2022
.Dt POLYBAR-DREC 1
.Sh NAME
.Nm polybar-drec
.Nd desktop recorder ipc for polybar
.Sh SYNOPSIS
.Nm
.Op Fl DCh
.Op Fl p Ar pid
.Sh OPTIONS
.Bl -tag -width indent
.It Fl D
show default message
.It Fl C
show current message
.It Fl h
show usage
.It Fl p
specify the polybar process id
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
