.Dd September 28, 2023
.Dt POLYBAR-RADIO 1
.Sh NAME
.Nm polybar-radio
.Nd radio player ipc for polybar, call this script without any option to stop/start the radio.
.Sh SYNOPSIS
.Nm
.Op -volume|+volume|msg|like
.Sh OPTIONS
.Bl -tag -width indent
.It msg
get current message
.It +volume/-volume
increase/decrease volume
.It like
toggle like
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
