.Dd September 28, 2023
.Dt POLYBAR-RADIO 1
.Sh NAME
.Nm polybar-radio
.Nd radio player ipc for polybar
.Sh SYNOPSIS
.Nm
.Op Fl CDdhlu
.Sh OPTIONS
.Bl -tag -width indent
.It Fl C
show current message
.It Fl D
show default message
.It Fl d
decrease the volume of the mpv player
.It Fl h
show usage
.It Fl l
toggle current song like status
.It Fl u
increase the volume of the mpv player
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
