.Dd September 3, 2022
.Dt POLYBAR-CTL 1
.Sh NAME
.Nm polybar-ctl
.Nd polybar control
.Sh SYNOPSIS
.Nm
.Op Fl Shrs
.Sh OPTIONS
.Bl -tag -width indent
.It Fl S
stop polybar
.It Fl h
show usage
.It Fl r
restart polybar
.It Fl s
start polybar
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
