.Dd October 01, 2023
.Dt POLYBAR-SHUTDOWN 1
.Sh NAME
.Nm polybar-shutdown
.Nd cancellable shutdown ipc for polybar
.Sh SYNOPSIS
.Nm
.Op msg
.Sh OPTIONS
.Bl -tag -width indent
.It msg
get current message
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
