.Dd September 3, 2022
.Dt PSOUND 1
.Sh NAME
.Nm psound
.Nd change the volume of the specified application
.Sh SYNOPSIS
.Nm
.Op Fl hl
.Op Ar query
.Op Ar volume
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl l
list all the sound sources
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
