.Dd September 3, 2022
.Dt RAND 1
.Sh NAME
.Nm rand
.Nd get n-length random hexadecimal characters
.Sh SYNOPSIS
.Nm
.Op Fl h123456789
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl #
generate a hex number of that specific length
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
