.Dd September 3, 2022
.Dt RECAUDIO 1
.Sh NAME
.Nm recaudio
.Nd audio recorder for pulseaudio using ffmpeg
.Sh SYNOPSIS
.Nm
.Op Fl hi
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl i
select the audio source interactively
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
