.Dd September 3, 2022
.Dt ROFICALC 1
.Sh NAME
.Nm roficalc
.Nd run rofi calc script and copy its output to the clipboard
.Sh SYNOPSIS
.Nm
.Op Fl h
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
