.Dd October 24, 2022
.Dt SCREENSHOT 1
.Sh NAME
.Nm screenshot
.Nd screenshot utility that uses xscreenshot, pngcrop and slop
.Sh SYNOPSIS
.Nm
.Op Fl ah
.Sh OPTIONS
.Bl -tag -width indent
.It Fl a
take an area screenshot instead of one of the full screen
.It Fl h
show usage
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
