.Dd September 3, 2022
.Dt SIGCGT 1
.Sh NAME
.Nm sigcgt
.Nd display the signals a process is listening to in a human readable format
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Ar pid
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
