.Dd September 3, 2022
.Dt UNIHASH 1
.Sh NAME
.Nm unihash
.Nd convert files in the specified directory to the format hash.extension and
move duplicated ones to the repeated directory
.Sh SYNOPSIS
.Nm
.Op Fl Phq
.Op Ar dir
.Sh OPTIONS
.Bl -tag -width indent
.It Fl P
disable the prompt for a random number
.It Fl h
show usage
.It Fl q
run the program silently
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
