.Dd September 3, 2022
.Dt UPLOAD 1
.Sh NAME
.Nm upload
.Nd upload files to 0x0.st with ease
.Sh SYNOPSIS
.Nm
.Op Fl he
.Op Ar file
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl e
encrypt the file with a passphrase before uplaod
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/bin/issues
