#!/bin/sh

#
# mount and umount 
# my backup partition
#

OPT_MOUNT=false
OPT_UMOUNT=false
UUID='f69c82e2-0a9e-4197-ad67-13aa6450ad03'

main() {
	parsed_args=$(getopt -o muh -l mount,umount,help -n 'backupfs' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ] ; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-m | --mount ) OPT_MOUNT=true; shift ;;
			-u | --umount ) OPT_UMOUNT=true; shift ;;
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	$OPT_MOUNT || 
		$OPT_UMOUNT || 
			die 'mount or umount option must be specified'
	
	$OPT_MOUNT && 
		$OPT_UMOUNT && 
			die 'mount and umount options are mutually exclusive'

	lsblk -o UUID | grep -qE "^$UUID$" || 
		die 'storage device is not connected'

	if $OPT_MOUNT; then
		lsblk -o UUID,MOUNTPOINTS | grep -qE "^$UUID\s$" || 
			die 'partition is already mounted'
		
		sudo mount --uuid "$UUID" /back
		sudo chmod 777 /back
		sudo chown alpheratz:alpheratz /back
		exit 0
	fi

	lsblk -o UUID,MOUNTPOINTS | grep -qE "^$UUID\s$" && 
		die 'partition is not mounted'
	
	sudo umount /back 2>/dev/null || 
		die 'target is busy'
}

die() {
	printf "backupfs: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: backupfs [ -muh ]
	echo Options are:
	echo '     -m | --mount                   mount the backup partition'
	echo '     -u | --umount                  umount the backup partition'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
