#!/bin/sh

#
# download youtube video thumbnail
# in the highest quality
#

main() {
	parsed_args=$(getopt -o o:h -l output:,help -n 'dlthumb' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-o | --output ) out_filename="$2"; shift 2 ;;
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	video_id="$1"

	[ -z "$video_id" ] &&
		die 'you must specify a video id'

	[ -z "$out_filename" ] &&
		out_filename="thumb_$video_id.jpg"

	curl -s "https://img.youtube.com/vi/$video_id/maxresdefault.jpg" \
		 -o "$out_filename"
}

die() {
	printf "dlthumb: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: dlthumb [ -h ] [ -o FILENAME ] VIDEO_ID
	echo Options are:
	echo '     -o | --output                  specify the name of the output file'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
