#!/bin/sh

#
# download youtube video thumbnail
# in the highest quality
#

main() {
	parsed_args=$(getopt -o h -l help -n 'dlthumb' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	video_id="$1"

	[ -z "$video_id" ] && 
		die 'you must specify a video id'

	curl -s "https://img.youtube.com/vi/$video_id/maxresdefault.jpg" \
		 -o "thumb_$video_id.jpg"
}

die() {
	printf "error: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: dlthumb [ -h ] VIDEO_ID
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
