#!/bin/bash

#
# edit known config
# files and scripts
#


TARGET="$1"

case "$1" in
	alacritty ) vim ~/.alacritty.yml ;;
	vim ) vim ~/.vimrc ;;
	zsh ) vim ~/.zshrc ;;
	zprofile ) vim ~/.zprofile ;;
	xres ) vim ~/.Xresources ;;
	xinit ) vim ~/.xinitrc ;;	
	git ) vim ~/.gitconfig ;;
	htop ) vim ~/.config/htop/htoprc ;;
	i3 ) vim ~/.config/i3/config ;;
	polybar ) vim ~/.config/polybar/config ;;
	polylaunch ) vim ~/.config/polybar/launch.sh ;;
	picom ) vim ~/.config/picom/picom.conf ;;
	rofi ) vim ~/.config/rofi/theme.rasi ;;
	dunst ) vim ~/.config/dunst/dunstrc ;;
	* ) vim "$BASH_SOURCE" ;;
esac
