#!/bin/bash

#
# get the encoded date
# of a video
#

function main() {
	filename="$1"
	
	[ -z "$filename" ] && die 'filename cannot be empty'
	[ ! -f "$filename" ] && die 'file doesnt exist'
	
	data=$(mediainfo "$filename" | grep 'Encoded date' | head -n1)
	
	[ -z "$data" ] && die 'file has no encoded date field in metadata'

	echo $data | awk 'BEGIN { FS="[- :]" } { print $6$7$8$9$10$11 }'
}

function die() {
	printf "error: %s\n" "$@" >&2
	exit 1
}

main "$@"
