#!/bin/sh

main() {
	parsed_args=$(getopt -o h -l help -n 'previewmd' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	FILENAME="$1"

	[ -f "$FILENAME" ] || die 'file does not exist'

	pandoc --pdf-engine=xelatex "$FILENAME" -t pdf | zathura -

}

die() {
	printf "previewmd: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: previewmd [ -h ] FILE
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
