#!/bin/sh

# 
# change the volume of the specified
# application
#

QUERY
VOLUME

main() {
	parsed_args=$(getopt -o h -l help -n 'psound' -- "$@")
	getopt_exit_code=$?
	
	[ $getopt_exit_code -ne 0 ] && exit 1

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done
	
	QUERY="$1"
	VOLUME="$2"

	[ -z "$QUERY" ] && die 'you must specify a query'
	[ -z "$VOLUME" ] && die 'you must the volume level'

	match=$(pactl list sink-inputs | awk 'BEGIN { FS="\"" } /application\.name/{ print $2 }' | grep -iF "$QUERY" | head -n1)

	[ -z "$match" ] && die 'search query didnt match any application'

	sinkid=$(pactl list sink-inputs | grep -F "application.name = \"$match\"" -B 30 | rev | grep '# tupnI kniS' | cut -d '#' -f1 | rev)
	pactl set-sink-input-volume "$sinkid" "$VOLUME%"
}

die() {
	printf "error: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: psound [ -h ] QUERY VOLUME
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
