#!/bin/sh

#
# record the full screen or 
# the selected area
#

FFMPEG_SIZPOS_FLAGS='-s 1920x1080 -i :0.0'
FFMPEG_DURATION_FLAG=''

OPT_DURATION=false
OPT_WAIT=false
OPT_SELECTION=false
OPT_GIF=false
DURATION=1
WAIT=1
FPS=60

main() {
	parsed_args=$(getopt -o gd:w:sh -l gif,duration:,wait:,selection,help -n 'recvideo' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-g | --gif ) OPT_GIF=true; FPS=20; shift ;;
			-d | --duration ) OPT_DURATION=true; DURATION="$2"; shift 2 ;;
			-w | --wait ) OPT_WAIT=true; WAIT="$2"; shift 2 ;;
			-s | --selection ) OPT_SELECTION=true; shift ;;
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	[ "$WAIT" -eq "$WAIT" ] 2>/dev/null || die 'wait value must be a number'
	[ "$DURATION" -eq "$DURATION" ] 2>/dev/null || die 'duration value must be a number'
	[ "$WAIT" -gt 0 ] || die 'wait value must be a positive number'
	[ "$DURATION" -gt 0 ] || die 'duration value must be a positive number'

	if $OPT_WAIT; then
		sleep "$WAIT"
	fi

	if $OPT_DURATION; then
		FFMPEG_DURATION_FLAG="-t $DURATION"
	fi

	if $OPT_SELECTION; then
		FFMPEG_SIZPOS_FLAGS=$(slop --quiet --format="-s %wx%h -i :0.0+%x,%y") || exit 1
	fi	

	filename="$(date +%Y%m%d%H%M%S).mkv"

	ffmpeg -framerate $FPS \
		   -f x11grab \
		   $FFMPEG_SIZPOS_FLAGS \
		   $FFMPEG_DURATION_FLAG \
		   -c:v libx264 \
		   -crf 0 \
		   -preset ultrafast \
		   -y "$filename" 2>/dev/null>&2

	if $OPT_GIF; then
		gif_filename="$(basename "$filename" .mkv).gif"
		tempwd=$(mktemp -d)
		mv "$filename" "$tempwd"
		cd "$tempwd" || exit 1
		ffmpeg -i "$filename" \
			   -vf "fps=20,scale=-1:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
			   -loop 0 \
			   "$gif_filename" 2>/dev/null>&2
		cd - >/dev/null || exit 1
		mv "$tempwd/$gif_filename" .
		rm -rf "$tempwd"
	fi
}

die() {
	printf "recvideo: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: recvideo [ -gsh ] [ -d DURATION ] [ -w WAITSECONDS ]
	echo Options are:
	echo '     -g | --gif                     convert the video to gif'
	echo '     -s | --selection               select the area of the screen to record'
	echo '     -d | --duration                specify the length of the clip'
	echo '     -w | --wait                    wait X seconds before recording'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
