#!/bin/sh

#
# take a screenshot of the whole screen
# or the selected area and send 
# a notification using dunst
#

OPT_AREA=false
FORMAT="%Y%m%d%H%M%S.png"
OUTDIR="$HOME/.screenshots"

main() {
	parsed_args=$(getopt -o ah -l area,help -n 'screenshot' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-a | --area ) OPT_AREA=true; shift ;;
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	[ -d "$OUTDIR" ] || mkdir "$OUTDIR"

	if $OPT_AREA; then
		AREA=$(slop --quiet --format="%x,%y,%w,%h") || die 'selection cancelled'
		NOTIFICATION_CMD="notify-send 'area screenshot taken' 'file name: \$f'"
		scrot -d 1 -z "$FORMAT" -a "$AREA" -e "mv \$f $OUTDIR && $NOTIFICATION_CMD" 2>/dev/null
		exit 0
	fi

	NOTIFICATION_CMD="notify-send 'screenshot taken' 'file name: \$f'"
	scrot -z "$FORMAT" -e "mv \$f $OUTDIR && $NOTIFICATION_CMD"	
}

die() {
	printf "screenshot: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: screenshot [ -ah ]
	echo Options are:
	echo '     -a | --area                    take an area screenshot instead of the full screen'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
