#!/bin/sh

#
# take a screenshot of the selected area
# and send a notification using dunst
#

FORMAT="%Y%m%d%H%M%S.png"
OUTDIR="$HOME/.screenshots"
NOTIFICATION_CMD="notify-send 'area screenshot taken' 'file name: \$f'"

if ! test -d "$OUTDIR" ; then
	mkdir "$OUTDIR";
fi

scrot -zs "$FORMAT" -e "mv \$f $OUTDIR && $NOTIFICATION_CMD"
