#!/bin/sh

#
# select an area of the screen with text
# and copies it to the clipboard
#

main() {
	parsed_args=$(getopt -o h -l help -n 'sltx' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	temp=$(mktemp -d)

	cd "$temp" || exit 1
	scrot -s selection.png

	[ -f selection.png ] ||
		die 'selection cancelled'

	tesseract selection.png result 2>/dev/null>&2
	xclip -i -sel clipboard < result.txt
	rm -rf "$temp"

	notify-send 'success' 'text copied to the clipboard'
}

die() {
	printf "sltx: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: sltx [ -h ]
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
