#!/bin/sh

#
# upload a file from the terminal to 0x0.st
# with the ability to encrypt it before with a passphrase
#

opt_encrypt=false

main() {
	parsed_args=$(getopt -o eh -l encrypt,help -n 'upload' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-e | --encrypt ) opt_encrypt=true; shift 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	file="$1"

	if [ -z "$file" ]; then
		die 'you must specify a file'
	fi

	if [ ! -f "$file" ]; then
		die 'the file does not exist'
	fi

	if ! $opt_encrypt; then

		#
		# upload the file without
		# encryption
		#

		curl -s https://0x0.st -F"file=@$file"
		exit 0
	fi

	#
	# to decrypt it later with the passphrase
	# do gpg -qo filename -d filename.gpg
	#

	gpg -qc "$file" 2>/dev/null || exit 1
	curl -s https://0x0.st -F"file=@$file.gpg"
	rm "$file.gpg"
}

die() {
	printf "sltx: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: upload [ -he ] FILENAME
	echo Options are:
	echo '     -e | --encrypt                 encrypt the file with a passphrase before uplaod'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
