#!/bin/sh

#
# mount and unmount
# my backup partition
#

opt_mount=false
opt_unmount=false
uuid='f69c82e2-0a9e-4197-ad67-13aa6450ad03'

main()
{
	parsed_args=$(getopt -o hmu -n 'backupfs' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h ) usage ;;
			-m ) opt_mount=true; shift ;;
			-u ) opt_unmount=true; shift ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	$opt_mount ||
		$opt_unmount ||
			die 'mount or unmount option must be specified'

	$opt_mount &&
		$opt_unmount &&
			die 'mount and unmount options are mutually exclusive'

	lsblk -o UUID | grep -qE "^$uuid$" ||
		die 'storage device is not connected'

	if $opt_mount; then
		lsblk -o UUID,MOUNTPOINTS | grep -qE "^$uuid\s$" ||
			die 'partition is already mounted'

		sudo mount --uuid "$uuid" /back
		sudo chmod 777 /back
		sudo chown alpheratz:alpheratz /back
		exit 0
	fi

	lsblk -o UUID,MOUNTPOINTS | grep -qE "^$uuid\s$" &&
		die 'partition is not mounted'

	sudo umount /back 2>/dev/null ||
		die 'target is busy'
}

die()
{
	printf "backupfs: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: backupfs [-hmu]
	exit 0
}

main "$@"
