#!/bin/sh

main()
{
	parsed_args=$(getopt -o h -l help -n 'bookopen' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	path="$1"

	[ -z "$path" ] &&
		die 'path cannot be empty'

	find "$path" -maxdepth 1 -type f |
		rev | cut -d '/' -f1 | rev | sort | rofi -dmenu |
		xargs -I{} sh -c "test -f '${path}/{}' && zathura '${path}/{}'"

}

die()
{
	printf "bookopen: %s\n" "$@" >&2
	exit 1
}

show_help()
{
	echo Usage: bookopen [ -h ] LIBRARY_PATH
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
