#!/bin/sh

main()
{
	parsed_args=$(getopt -o h -n 'bookopen' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h ) usage ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	library_dir="$1"

	test -z "$library_dir" &&
		die 'you must specify a library directory'

	test -d "$library_dir" ||
		die "$library_dir: not a directory"

	books=$(find "$library_dir" -maxdepth 1 -type f |
		rev | cut -d '/' -f1 | rev | sort)

	book=$(echo "$books" | rofi -dmenu -i -p 'book')

	test -f "$library_dir/$book" &&
		zathura "$library_dir/$book"
}

die()
{
	printf "bookopen: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: bookopen [-h] dir
	exit 0
}

main "$@"
