#!/bin/sh

#
# get the encoded date
# of a video
#

main()
{
	parsed_args=$(getopt -o h -n 'encdate' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) usage ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	filename="$1"

	[ -z "$filename" ] &&
		die 'filename cannot be empty'

	[ -f "$filename" ] ||
		die 'file does not exist'

	data=$(
		mediainfo "$filename" |
		grep 'Encoded date' |
		head -n1
	)

	[ -z "$data" ] &&
		die 'file has no encoded date field in metadata'

	echo "$data" |
		tr -s ' ' ' ' |
		awk 'BEGIN { FS="[- :]" } { print $6$7$8$9$10$11 }'
}

die()
{
	printf "encdate: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: encdate [-h] file
	exit 0
}

main "$@"
