#!/bin/sh

#
# print the exit code of
# the specified command
#

main() {
	parsed_args=$(getopt -o h -l help -n 'exode' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	cmd="$@"

	[ -z "$cmd" ] &&
		die 'command cannot be empty'

	"$cmd" 2>/dev/null >&2
	echo $?
}

die() {
	printf "exode: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: exode [ -h ]
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
