#!/bin/sh

#
# create a shell script
# using a template file
#

main()
{
	parsed_args=$(getopt -o h -l help -n 'mksh' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	filename="$1"

	[ -z "$filename" ] &&
		die 'filename cannot be empty'

	[ -f "$filename" ] &&
		die 'file already exists'

	echo "$filename" | grep -qE '^[a-zA-Z0-9\-]+$' ||
		die 'use only alphanumeric characters'

	cat <<EOF > "$filename"
#!/bin/sh

main()
{
	parsed_args=\$(getopt -o h -l help -n '$filename' -- "\$@")
	getopt_exit_code=\$?

	if [ \$getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "\$parsed_args"

	while :; do
		case "\$1" in
			-h | --help ) show_help; exit 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done
}

die()
{
	printf "$filename: %s\\n" "\$@" >&2
	exit 1
}

show_help()
{
	echo Usage: $filename [ -h ]
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "\$@"
EOF

	chmod +x "$filename"
}

die()
{
	printf "mksh: %s\n" "$@" >&2
	exit 1
}

show_help()
{
	echo Usage: mksh [ -h ] FILENAME
	echo Options are:
	echo '     -h | --help                    display this message and exit'
}

main "$@"
