#!/bin/sh

#
# cancellable shutdown
# ipc for polybar
#

PS_THEME_BG_COLOR="FF0000"
PS_THEME_FG_COLOR="FFFFFF"

PS_RUNTIME_PATH="$XDG_RUNTIME_DIR/polybar-shutdown"
PS_PID_PATH="$PS_RUNTIME_PATH/self.pid"
PS_CURRENT_MSG_PATH="$PS_RUNTIME_PATH/message"

main()
{
	umask 022
	mkdir -p "$PS_RUNTIME_PATH"

	case "$1" in
		msg ) get_message; return ;;
	esac

	toggle_shutdown_on_off
}

get_message()
{
	if test -f "$PS_PID_PATH" && /bin/kill -0 "$(cat "$PS_PID_PATH")"; then
		head -n1 "$PS_CURRENT_MSG_PATH"
	else
		echo "%{A1:polybar-shutdown:}%{B#$PS_THEME_BG_COLOR}%{F#$PS_THEME_FG_COLOR}  󰐥  %{A}"
	fi
}

set_message()
{
	echo "$@" > "$PS_CURRENT_MSG_PATH"
	polybar-msg action "#shutdown.hook.0"
}

toggle_shutdown_on_off()
{
	if test -f "$PS_PID_PATH" && /bin/kill -0 "$(cat "$PS_PID_PATH")"; then
		stop_shutdown
	else
		start_shutdown
	fi
}

start_shutdown()
{
	notify-send 'Warning' 'The computer will shutdown after 10 seconds.'

	echo $$ > "$PS_PID_PATH"

	for i in $(seq 10 -1 1); do
		set_message "%{A1:polybar-shutdown:}%{B#$PS_THEME_BG_COLOR}%{F#$PS_THEME_FG_COLOR}  󰔛 ${i}s  %{A}"
		sleep 1
	done

	set_message "%{B#$PS_THEME_BG_COLOR}%{F#$PS_THEME_FG_COLOR}  ...  "
	systemctl poweroff
}

stop_shutdown()
{
	/bin/kill -s KILL "$(cat "${PS_PID_PATH}")"
	polybar-msg action "#shutdown.hook.0"
}

main "$@"
