#!/bin/sh

#
# radio player
# ipc for polybar
# inspiration and links taken from:
# https://github.com/Carbon-Bl4ck/Rofi-Beats
#

PR_THEME_BG_COLOR="FCE702"
PR_THEME_FG_COLOR="000000"
PR_THEME_HEART_COLOR="FF0000"

PR_DATA_PATH="$XDG_DATA_HOME/polybar-radio"
PR_HISTORY_PATH="$PR_DATA_PATH/history"
PR_FAVS_PATH="$PR_DATA_PATH/favs"

PR_RUNTIME_PATH="$XDG_RUNTIME_DIR/polybar-radio"
PR_PID_PATH="$PR_RUNTIME_PATH/self.pid"
PR_CURRENT_MSG_PATH="$PR_RUNTIME_PATH/message"
PR_CURRENT_SONG_PATH="$PR_RUNTIME_PATH/song"
PR_RADIO_SOCKET_PATH="$PR_RUNTIME_PATH/socket"

PR_RADIOS=$(printf "%s\n" \
	'https://play.streamafrica.net/lofiradio' \
	'http://stream.zeno.fm/fyn8eh3h5f8uv' \
	'http://stream.zeno.fm/f3wvbbqmdg8uv' \
	'http://stream.zeno.fm/0r0xa792kwzuv' \
	'https://live.radiospinner.com/lofi-hip-hop-64' \
	'https://media-ssl.musicradio.com/SmoothChill' \
)

main()
{
	umask 022

	mkdir -p "$PR_DATA_PATH"
	mkdir -p "$PR_RUNTIME_PATH"

	touch "$PR_HISTORY_PATH"
	touch "$PR_FAVS_PATH"

	case "$1" in
		msg      ) get_message;         return ;;
		+volume  ) increase_volume +5;  return ;;
		-volume  ) increase_volume -5;  return ;;
		like     ) toggle_like;         return ;;
	esac

	toggle_radio_on_off
}

get_message()
{
	if test -f "$PR_PID_PATH" && /bin/kill -0 "$(cat "$PR_PID_PATH")"; then
		head -n1 "$PR_CURRENT_MSG_PATH"
	else
		# nothing is playing
		echo "%{A1:polybar-radio:}%{B#$PR_THEME_BG_COLOR}%{F#$PR_THEME_FG_COLOR}  󰐊 Play  %{F-}%{B-}%{A}"
	fi
}

set_message()
{
	echo "$@" > "$PR_CURRENT_MSG_PATH"
	polybar-msg action "#radio.hook.0"
}

increase_volume()
{
	delta_vol=$1
	current_vol=$(echo '{ "command": ["get_property", "volume"]  }' |
		netcat -U "$PR_RADIO_SOCKET_PATH" | head -n1 | jq '.data' | cut -d. -f1)
	next_vol=$((current_vol+delta_vol))

	if [ "$next_vol" -gt 100 ]; then
		next_vol=100
	elif [ "$next_vol" -lt 0 ]; then
		next_vol=0
	fi

	echo "{ \"command\": [\"set_property\", \"volume\", \"$next_vol\"] }" |
		netcat -U "$PR_RADIO_SOCKET_PATH" | head -n1
}

toggle_like()
{
	song="$(cat "$PR_CURRENT_SONG_PATH")"

	if grep -qF "$song" "$PR_FAVS_PATH"; then
		heart='󱢠'
		newlist=$(grep -v -F "$song" "$PR_FAVS_PATH")
		echo "$newlist" > "$PR_FAVS_PATH"
	else
		heart='󰣐'
		echo "$song" >> "$PR_FAVS_PATH"
	fi

	heartmsg="%{A1:polybar-radio like:}%{F#$PR_THEME_HEART_COLOR}%{T2}$heart%{T-}  %{A}"
	songmsg="%{A3:polybar-radio:}%{B#$PR_THEME_BG_COLOR}%{F#$PR_THEME_FG_COLOR}  %{T2}󰝚%{T-}  $song  $heartmsg%{A}"

	set_message "%{A5:polybar-radio -volume:}%{A4:polybar-radio +volume:}$songmsg%{A}%{A}"
}

toggle_radio_on_off()
{
	if test -f "$PR_PID_PATH" && /bin/kill -0 "$(cat "$PR_PID_PATH")"; then
		stop_radio
	else
		start_radio
	fi
}

start_radio()
{
	radio_url="$(printf "%s" "$PR_RADIOS" | shuf -n1)"

	mpv --volume=60 \
		--input-ipc-server="${PR_RADIO_SOCKET_PATH}" \
		-title='polybar-radio' --no-video "$radio_url" 2>/dev/null | {

		echo $! > "${PR_PID_PATH}"

		set_message "%{A1:polybar-radio:}%{B#$PR_THEME_BG_COLOR}%{F#$PR_THEME_FG_COLOR}   Loading...  %{F-}%{B-}%{A}"

		while read -r line; do
			heart='󱢠'
			timestamp=$(date +'%Y %b %d %H:%M')
			song=$(echo "$line" | grep -E '^.?icy-title' | cut -d ':' -f2-)

			[ -z "$song" ] && continue

			echo "$song" > "${PR_CURRENT_SONG_PATH}"

			tail -n5 "$PR_HISTORY_PATH" | grep -q "$song" ||
				echo "$timestamp ➜  $song" >> "$PR_HISTORY_PATH"

			grep -qF "$song" "$PR_FAVS_PATH" &&
				heart='󰣐'

			heartmsg="%{A1:polybar-radio like:}%{F#$PR_THEME_HEART_COLOR}%{T2}$heart%{T-}  %{A}"
			songmsg="%{A3:polybar-radio:}%{B#$PR_THEME_BG_COLOR}%{F#$PR_THEME_FG_COLOR}  %{T2}󰝚%{T-}  $song  $heartmsg%{A}"

			set_message "%{A5:polybar-radio -volume:}%{A4:polybar-radio +volume:}$songmsg%{A}%{A}"
		done
	} &
}

stop_radio()
{
	/bin/kill -s KILL "$(cat "${PR_PID_PATH}")"
	polybar-msg action "#radio.hook.0"
}

main "$@"
