#!/bin/sh

#
# desktop recorder
# ipc for polybar
#

# colors
bgcolor='000000'
fgcolor='FF0000'

opt_default=false
opt_current=false

main()
{
	parsed_args=$(getopt -o DChp: -n 'polybar-drec' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-D ) opt_default=true; shift ;;
			-C ) opt_current=true; shift ;;
			-p ) barpid=$2; shift 2 ;;
			-h ) usage ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	$opt_default &&
		show_default

	$opt_current &&
		show_current

	if [ -f /tmp/record.pid ]; then
		stop_recording
	else
		start_recording
	fi
}

ellapsed()
{
	since="$1"
	now=$(date +%s)
	delta=$((now - since))
	minutes=$((delta / 60))
	seconds=$((delta % 60))
	printf "%02d:%02d\n" $minutes $seconds
}

start_recording()
{
	start=$(date +%s)
	recname=$(date +%Y%m%d%H%M%S)
	filename="$HOME/.screenrec/$recname.mkv"

	sink=$(pactl list short sources | \
		awk '{ print $2 }' | \
		grep 'monitor$' | \
		head -n1
	)

	# rw-r--r-- for files
	# rwxr-xr-x for directories
	umask 022

	mkdir -p "$HOME/.screenrec"

	echo "%{B#$bgcolor}%{F#$fgcolor}   Starting  " > /tmp/record
	polybar-msg -p "$barpid" hook rec 2

	ffmpeg \
		   -f pulse \
		   -ac 2 -i "$sink" \
		   -f x11grab \
		   -framerate 60 \
		   -i :0.0 \
		   -c:v libx264 \
		   -crf 0 \
		   -preset ultrafast \
		   -y "$filename" 2>/dev/null>&2 &

	echo "$!" > /tmp/record.pid

	sleep 0.5
	while [ -f /tmp/record.pid ]; do
		echo "%{A1:polybar-drec -p $barpid:}%{B#$bgcolor}%{F#$fgcolor}   STOP $(ellapsed "$start")  %{A}" > /tmp/record
		polybar-msg -p "$barpid" hook rec 2
		sleep 1
	done;
}

stop_recording()
{
	polybar-msg -p "$barpid" hook rec 1
	/bin/kill -s INT "$(cat /tmp/record.pid)"

	rm -f /tmp/record.pid
	rm -f /tmp/record
}

show_default()
{
	echo "%{A1:polybar-drec -p $barpid:}%{B#$bgcolor}%{F#$fgcolor}   Rec  %{A}"
	exit 0
}

show_current()
{
	cat /tmp/record
	exit 0
}

die()
{
	printf "polybar-drec: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: polybar-drec [-DCh] [-p pid]
	exit 0
}

main "$@"
