#!/bin/sh

#
# change the volume of the specified
# application
#

opt_list=false

main()
{
	parsed_args=$(getopt -o hl -n 'psound' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h ) usage ;;
			-l ) opt_list=true; shift ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	if $opt_list; then
		pasid | cut -d '-' -f2- | grep -o '[^ ].*'
		exit 0
	fi

	query="$1"
	volume="$2"

	[ -z "$query" ] &&
		die 'you must specify a query'

	[ -z "$volume" ] &&
		die 'you must specify the volume level'

	[ "$volume" -eq "$volume" ] 2>/dev/null ||
		die 'volume must be a number'

	[ "$volume" -lt 0 ] &&
		volume=0

	sinkid=$(pasid -q "$query")

	[ -z "$sinkid" ] &&
		die 'search query didnt match any application'

	pactl set-sink-input-volume "$sinkid" "$volume%"
}

die()
{
	printf "psound: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: psound [-hl] query volume
	exit 0
}

main "$@"
