#!/bin/sh

#
# get n-length random
# hexadecimal characters
#

main()
{
	if [ -n "$1" ] ; then
		case "$1" in
			-h ) usage ;;
			-* ) length=$(printf "%s" "$1" | cut -d'-' -f2); shift; break ;;
			* ) usage ;;
		esac
	fi

	[ -z "$length" ] &&
		length=16

	[ "$length" -eq "$length" ] 2> /dev/null ||
		die 'invalid length'

	[ "$length" -lt 1 ] &&
		die 'invalid length'

	head -c "$length" /dev/random | od -An -w2 -t x1 - | tr -d ' ' | tr -d '\n' | head -c "$length"
}

die()
{
	printf "rand: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: rand [-h123456789]
	exit 0
}

main "$@"
