#!/bin/sh

#
# audio recorder for
# pulseaudio using ffmpeg
#

opt_interactive=false

trap '' INT

main() {
	parsed_args=$(getopt -o ih -l interactive,help -n 'recaudio' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-i | --interactive ) opt_interactive=true; shift 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	if $opt_interactive; then
		audio_source=$(
			pactl list short sources |
			awk '{ print $2 }' |
			rofi -dmenu -p 'audio source'
		)
	else
		audio_source="$1"
	fi

	[ -z "$audio_source" ] &&
		die 'no source specified'

	pactl list short sources | awk '{ print $2 }' | grep -qE "^$audio_source$" ||
		die 'invalid audio source'

	ffmpeg -f pulse \
		   -ac 2 -i "$audio_source" \
		   -ab 320k -acodec libmp3lame \
		   -y "$(date +%Y%m%d%H%M%S).mp3" 2>/dev/null>&2
}

die() {
	printf "recaudio: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: recaudio [ -ih ] SOURCE
	echo Options are:
	echo '     -i | --interactive             select the audio source interactively'
	echo '     -h | --help                    display this message and exit'
}

main "$@"
