#!/bin/sh

#
# record the full screen or
# the selected area
#

ffmpeg_sizpos_flags='-i :0.0'
ffmpeg_duration_flag=''

opt_duration=false
opt_wait=false
opt_selection=false
opt_gif=false
duration=1
waitseconds=1
fps=60

trap '' INT

main()
{
	parsed_args=$(getopt -o ghsd:w: -n 'recvideo' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-g ) opt_gif=true; fps=20; shift ;;
			-h ) usage ;;
			-s ) opt_selection=true; shift ;;
			-d ) opt_duration=true; duration="$2"; shift 2 ;;
			-w ) opt_wait=true; waitseconds="$2"; shift 2 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	[ "$waitseconds" -eq "$waitseconds" ] 2>/dev/null || die 'wait value must be a number'
	[ "$duration" -eq "$duration" ] 2>/dev/null || die 'duration value must be a number'
	[ "$waitseconds" -gt 0 ] || die 'wait value must be a positive number'
	[ "$duration" -gt 0 ] || die 'duration value must be a positive number'

	if $opt_wait; then
		sleep "$waitseconds"
	fi

	if $opt_duration; then
		ffmpeg_duration_flag="-t $duration"
	fi

	if $opt_selection; then
		ffmpeg_sizpos_flags=$(slop --quiet --format="-s %wx%h -i :0.0+%x,%y") || exit 1
	fi

	filename="$(date +%Y%m%d%H%M%S).mkv"

	ffmpeg -framerate $fps \
		   -f x11grab \
		   $ffmpeg_sizpos_flags \
		   $ffmpeg_duration_flag \
		   -c:v libx264 \
		   -crf 0 \
		   -preset ultrafast \
		   -y "$filename" 2>/dev/null>&2

	if $opt_gif; then
		gif_filename="$(basename "$filename" .mkv).gif"
		tempwd=$(mktemp -d)
		mv "$filename" "$tempwd"
		cd "$tempwd" || exit 1
		ffmpeg -i "$filename" \
			   -vf "fps=20,scale=-1:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
			   -loop 0 \
			   "$gif_filename" 2>/dev/null>&2
		cd - >/dev/null || exit 1
		mv "$tempwd/$gif_filename" .
		rm -rf "$tempwd"
	fi
}

die()
{
	printf "recvideo: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: recvideo [-ghs] [-d seconds] [-w seconds]
	exit 0
}

main "$@"
