#!/bin/sh

#
# run rofi calc script and
# copy its output to the clipboard
#

main()
{
	parsed_args=$(getopt -o h -n 'roficalc' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h ) usage ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	rofi -show calc \
		 -modi calc \
		 -no-show-match \
		 -no-sort \
		 -terse \
		 -calc-command 'echo -n {result} | xclip -i -sel clipboard' \
		 -no-history \
		 -hint-welcome '' \
		 -hint-result ''
}

usage()
{
	echo usage: roficalc [-h]
	exit 0
}

main "$@"
