#!/bin/sh

#
# take a screenshot of the whole screen
# or the selected area and send
# a notification using dunst
#

opt_area=false
outdir="$HOME/.screenshots"

main()
{
	parsed_args=$(getopt -o ah -n 'screenshot' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-a ) opt_area=true; shift ;;
			-h ) usage ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	[ -d "$outdir" ] ||
		mkdir "$outdir"

	if $opt_area; then
		area=$(slop --quiet) || die 'selection cancelled'
		temp_dir=$(mktemp -d)
		ss=$(xscreenshot -d "$temp_dir" -p)
		ss_name=$(basename "$ss")
		pngcrop "$area" "$ss" "$outdir/$ss_name"
		notify-send 'area screenshot taken' "file name: $ss_name"
		rm "$ss"
		rmdir "$temp_dir"
		exit 0
	fi

	ss_name=$(basename "$(xscreenshot -d "$outdir" -p)")
	notify-send 'screenshot taken' "file name: $ss_name"
}

die()
{
	printf "screenshot: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: screenshot [-ah]
	exit 0
}

main "$@"
