#!/bin/sh

gtts_cli_extra_flags=""

if test "$1" = "-slow"; then
	gtts_cli_extra_flags="--slow"
	shift
fi

trans -brief :no "$*" | \
	tee /dev/stderr | \
		gtts-cli --lang no $gtts_cli_extra_flags -f - | \
			mpv --really-quiet -
