#!/bin/sh

#
# upload a file from the terminal to 0x0.st
# with the ability to encrypt it before with a passphrase
#

opt_encrypt=false

main()
{
	parsed_args=$(getopt -o eh -n 'upload' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0 ]; then
		exit 1
	fi

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-h ) usage ;;
			-e ) opt_encrypt=true; shift 1 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	file="$1"

	[ -z "$file" ] &&
		die 'you must specify a file'

	[ -f "$file" ] ||
		die 'the file does not exist'

	if $opt_encrypt; then

		#
		# to decrypt it later with the passphrase
		# do gpg -qo filename -d filename.gpg
		#

		gpg -qc "$file" 2>/dev/null ||
			die 'gpg encryption failed or cancelled'

		curl -s https://0x0.st -F"file=@$file.gpg"
		rm "$file.gpg"

		exit 0
	fi

	#
	# upload the file without
	# encryption
	#

	curl -s https://0x0.st -F"file=@$file"
}

die()
{
	printf "upload: %s\n" "$@" >&2
	exit 1
}

usage()
{
	echo usage: upload [-he] file
	exit 0
}

main "$@"
